### ISSUE TITLE
Fresh setup of OH 2.4, missing conf with items, rules etc.

### ISSUE THREAD

**Issue by piejanssens** [openhab/openhab-syno-spk#147]
I have setup OH 2.4 using the SPK.
Fresh setup of all my bindings, things and items (and even rules using the rule builder) through PaperUI.
I don't see the 'conf' folder being created or any items/things/... files in  `/volume1/openHAB/userdata`.
Is that normal because I did everything through PaperUI? How do I export my config or create a backup now?

**Comment by Tost69** [comment]
Hi,

the bindings, things and items you've setup with PaperUI are stored somewhere. Otherwise you couldn't see them in PaperUI/Control, right?

On my 2bay Syno the installation has created the folder /volume1/@appstore /openHAB (I've selected to install to volume 1).

Depending on your chosen settings during the setup both folders conf and userdata were created
- either in the userhome of user openhab (/var/services/homes/openhab/userdata and /var/services/homes/openhab/conf)
- or in the public folder (/volume1/public/userdata, /volume1/public/conf)
- or within another folder you'd specified

Installation also creates symbolic links (/volume1/@appstore/openHAB/conf, /volume1/@appstore/openHAB/userdata) which will point to the created userdata and conf folders.
Please check /volume1/@appstore /openHAB with SSH where data is stored. 

Things created with PaperUI are stored in userdata/jsondb/org.eclipse.smarthome.core.thing.Thing.json

Kind regards, Tom

**Comment by cniweb** [comment]
@piejanssens This is not a openhab/openhab-syno-spk issue, read the OH docs. Can I close this issue?

**Comment by piejanssens** [comment]
@cniweb 
I still don't know where to put the files. I don't have a 'conf' folder in the /volume1/public/openHAB directory. I created one afterwards but OH doesn't seem to pick up anything (created a test file ` /volume1/public/openHAB/conf/sitemaps/demo.sitemap`) This was a fresh install of 2.4.

**Comment by piejanssens** [comment]
After a restart it was working. So recreating the symlinks was key for me.
