### ISSUE TITLE
Installation of 2.0.0-beta2-DSM6-RC fails

### ISSUE THREAD

**Issue by timwest73** [openhab/openhab-syno-spk#24]
When trying to do a manual package install of the OpenHAB 2 beta on my 1512+ I get the following error message. "Port undefined configured for this package is either used by another service or reserved for system. Please disable or modify the conflicting service, or contact the developer to modify the package configuration"

I've made sure that nothing in /usr/local/etc/services.d/ refers to the ports 8080 or 5555. Not sure why it refers to port "undefined" though. 

I'm running DSM 6.0-7321 Update 3

Any help would be appreciated.

Regards
Tim

**Comment by timwest73** [comment]
I've resolved this after uninstalling everything including Java and re-installing, however I now have the some problem as a few other people in that the package won't start.

**Comment by cniweb** [comment]
Hi @timwest73,

you can try the new release!

Regards
Chris

**Comment by timwest73** [comment]
Hi Chris,

Sorry I'm on holidays away from home at the moment. Home in week or so.

Regards
Tim

**Comment by tseroo** [comment]
Hi,

I'm having the same problem. None of the DSM 6 packages is working for me. I'm running DSM 6.0.2-8451 Update 2 and I've tried 

- OpenHAB-2.0.0-beta3-DSM6-syno-noarch-0.001.spk
- OpenHAB-2.0.0.007-SNAPSHOT-DSM6-syno-noarch-0.001.spk
- OpenHAB-1.8.3-DSM6-syno-noarch-0.001.spk

Error message is "Port undefined configured for this package is either used by another service or reserved for system. Please disable or modify the conflicting service, or contact the developer to modify the package configuration".

Port 8080 is not in use:
`root@ds412:/usr/local/etc/services.d#  netstat -an | grep 8080`
`root@ds412:/usr/local/etc/services.d#`

That's written in the synopkg.log:
2016/11/06 20:13:50     (system) trigger         :
                        Begin:  /bin/tar xf /volume1/@tmp/upload_tmp.319140 -C /volume1/@tmp/581F80EE0 INFO --no-same-owner
2016/11/06 20:13:50     (system) trigger         :
                        End:    /bin/tar xf /volume1/@tmp/upload_tmp.319140 -C /volume1/@tmp/581F80EE0 INFO --no-same-owner     ret=[0]
2016/11/06 20:13:50     (system) trigger         :
                        Begin:  /bin/tar xf /volume1/@tmp/upload_tmp.319140 -C /volume1/@tmp/581F80EE0 conf --no-same-owner
/bin/tar: conf: Not found in archive
/bin/tar: Exiting with failure status due to previous errors
2016/11/06 20:13:50     (system) trigger         :
                        End:    /bin/tar xf /volume1/@tmp/upload_tmp.319140 -C /volume1/@tmp/581F80EE0 conf --no-same-owner     ret=[2]
2016/11/06 20:13:50     (system) trigger        OpenHAB 1.8.3-001:
                        Begin:  /bin/tar xf /volume1/@tmp/upload_tmp.319140 -C /volume1/@tmp/581F80EE0 scripts/start-stop-status --no-same-owner --no-same-permissions
2016/11/06 20:13:50     (system) trigger        OpenHAB 1.8.3-001:
                        End:    /bin/tar xf /volume1/@tmp/upload_tmp.319140 -C /volume1/@tmp/581F80EE0 scripts/start-stop-status --no-same-owner --no-same-permissions  ret=[0]
2016/11/06 20:13:50     (system) trigger        OpenHAB 1.8.3-001:
                        Begin:  /bin/tar xf /volume1/@tmp/upload_tmp.319140 -C /volume1/@tmp/581F80EE0 scripts/preinst --no-same-owner --no-same-permissions
2016/11/06 20:13:50     (system) trigger        OpenHAB 1.8.3-001:
                        End:    /bin/tar xf /volume1/@tmp/upload_tmp.319140 -C /volume1/@tmp/581F80EE0 scripts/preinst --no-same-owner --no-same-permissions    ret=[0]
2016/11/06 20:13:50     (system) trigger        OpenHAB 1.8.3-001:
                        Begin:  /bin/tar xf /volume1/@tmp/upload_tmp.319140 -C /volume1/@tmp/581F80EE0 scripts/postinst --no-same-owner --no-same-permissions
2016/11/06 20:13:50     (system) trigger        OpenHAB 1.8.3-001:
                        End:    /bin/tar xf /volume1/@tmp/upload_tmp.319140 -C /volume1/@tmp/581F80EE0 scripts/postinst --no-same-owner --no-same-permissions   ret=[0]
2016/11/06 20:13:50     (system) trigger        OpenHAB 1.8.3-001:
                        Begin:  /bin/tar xf /volume1/@tmp/upload_tmp.319140 -C /volume1/@tmp/581F80EE0 scripts/preuninst --no-same-owner --no-same-permissions
2016/11/06 20:13:50     (system) trigger        OpenHAB 1.8.3-001:
                        End:    /bin/tar xf /volume1/@tmp/upload_tmp.319140 -C /volume1/@tmp/581F80EE0 scripts/preuninst --no-same-owner --no-same-permissions  ret=[0]
2016/11/06 20:13:50     (system) trigger        OpenHAB 1.8.3-001:
                        Begin:  /bin/tar xf /volume1/@tmp/upload_tmp.319140 -C /volume1/@tmp/581F80EE0 scripts/postuninst --no-same-owner --no-same-permissions
2016/11/06 20:13:50     (system) trigger        OpenHAB 1.8.3-001:
                        End:    /bin/tar xf /volume1/@tmp/upload_tmp.319140 -C /volume1/@tmp/581F80EE0 scripts/postuninst --no-same-owner --no-same-permissions ret=[0]
2016/11/06 20:13:50     (system) trigger        OpenHAB 1.8.3-001:
                        Begin:  /bin/tar xf /volume1/@tmp/upload_tmp.319140 -C /volume1/@tmp/581F80EE0 scripts/preupgrade --no-same-owner --no-same-permissions
/bin/tar: scripts/preupgrade: Not found in archive
/bin/tar: Exiting with failure status due to previous errors
2016/11/06 20:13:50     (system) trigger        OpenHAB 1.8.3-001:
                        End:    /bin/tar xf /volume1/@tmp/upload_tmp.319140 -C /volume1/@tmp/581F80EE0 scripts/preupgrade --no-same-owner --no-same-permissions ret=[2]
2016/11/06 20:13:50     (system) trigger        OpenHAB 1.8.3-001:
                        Begin:  /bin/tar xf /volume1/@tmp/upload_tmp.319140 -C /volume1/@tmp/581F80EE0 scripts/postupgrade --no-same-owner --no-same-permissions
/bin/tar: scripts/postupgrade: Not found in archive
/bin/tar: Exiting with failure status due to previous errors
2016/11/06 20:13:50     (system) trigger        OpenHAB 1.8.3-001:
                        End:    /bin/tar xf /volume1/@tmp/upload_tmp.319140 -C /volume1/@tmp/581F80EE0 scripts/postupgrade --no-same-owner --no-same-permissions        ret=[2]
2016/11/06 20:13:50     (system) trigger        OpenHAB 1.8.3-001:
                        Begin:  /bin/rm -rf /volume1/@tmp/581F80EE0
2016/11/06 20:13:50     (system) trigger        OpenHAB 1.8.3-001:
                        End:    /bin/rm -rf /volume1/@tmp/581F80EE0     ret=[0]

Any ideas??
Thanks,
Harry

**Comment by timwest73** [comment]
Hi Tseroo. Sorry I can't help. I eventually gave up on Openhab and I'm running Domoticz on DSM 6. Not as flexible, but its so much easier to setup and it works. Good luck.
